# Generated by Django 4.1.4 on 2023-01-03 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0003_alter_ability_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ability',
            name='ability_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='ability',
            name='description',
            field=models.CharField(max_length=4096),
        ),
    ]
