# Generated by Django 4.1.4 on 2023-01-03 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0004_alter_ability_ability_id_alter_ability_description'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='ability',
            index=models.Index(fields=['ability_id'], name='analyzer_ab_ability_a68c3e_idx'),
        ),
    ]
